# netlify.toml

[build]
  command = "ng build"
  # Verifica que esta sea tu carpeta de salida del navegador
  publish = "dist/casa-laureles/browser"

# Especifica explícitamente el directorio de funciones aquí
[functions]
  # Verifica que esta sea tu carpeta de salida del servidor (que contiene server.mjs)
  directory = "dist/casa-laureles/server"
  # node_bundler = "esbuild" # Puedes probar a añadir esto si Netlify lo sugiere

# Las redirecciones siguen siendo importantes
[[redirects]]
  from = "/*"
  # Asegúrate que 'server' es el nombre correcto (de server.ts -> server.mjs)
  to = "/.netlify/functions/server"
  status = 200
  force = true # Importante para que capture todas las rutas
