# netlify.toml (Intento con sección [functions])

[build]
  command = "ng build"
  # Verifica que esta sea tu carpeta de salida del navegador
  publish = "dist/casa-laureles/browser"
  # Quitamos 'functions' de aquí

# Usamos la sección dedicada [functions]
[functions]
  # Verifica que esta sea tu carpeta de salida del servidor
  directory = "dist/casa-laureles/server"
  # node_bundler = "esbuild" # Puedes probar a descomentar esto si el error persiste

# Las redirecciones siguen igual
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server" # Asumiendo que Netlify llama 'server' a la función
  status = 200
  force = true